version: '3.2'

services:
  elasticsearch01:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    # volumes:
    #   - type: bind
    #     source: ./elasticsearch/config/elasticsearch.yml
    #     target: /usr/share/elasticsearch/config/elasticsearch.yml
    #     read_only: true
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=elasticsearch01
      - discovery.seed_hosts=elasticsearch02
      - cluster.initial_master_nodes=elasticsearch01,elasticsearch02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # - "ELASTIC_PASSWORD:changeme"
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      # discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  elasticsearch02:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    # volumes:
    #   - type: bind
    #     source: ./elasticsearch/config/elasticsearch.yml
    #     target: /usr/share/elasticsearch/config/elasticsearch.yml
    #     read_only: true
    ports:
      - "9202:9200"
      - "9302:9300"
    environment:
      - node.name=elasticsearch02
      - discovery.seed_hosts=elasticsearch01
      - cluster.initial_master_nodes=elasticsearch01,elasticsearch02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # - "ELASTIC_PASSWORD:changeme"
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      # discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk

  # logstash:
  #   build:
  #     context: logstash/
  #     args:
  #       ELK_VERSION: $ELK_VERSION
  #   volumes:
  #     - type: bind
  #       source: ./logstash/config/logstash.yml
  #       target: /usr/share/logstash/config/logstash.yml
  #       read_only: true
  #     - type: bind
  #       source: ./logstash/pipeline
  #       target: /usr/share/logstash/pipeline
  #       read_only: true
  #   ports:
  #     - "5044:5044"
  #     - "5000:5000/tcp"
  #     - "5000:5000/udp"
  #     - "9600:9600"
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
  #   networks:
  #     - elk
  #   depends_on:
  #     - elasticsearch01
  #     - elasticsearch02
  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch01
      - elasticsearch02
networks:
  elk:
    driver: bridge

